[project]
name = "aiogram-minecraft-mod-launcher"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.22.0",
    "environs>=14.3.0",
    "httpx>=0.28.1",
    "scrapling>=0.3.1",
]
